# Note: define resource type in Kubernetes and OpenShift environment
apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: golang-codeready-workspace
  name: golang-codeready-workspace
  namespace: codeready-workspace  ##CHANGE ME
spec: 
  ports:
    # the port that this service should serve on
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: golang-codeready-workspace
  type: NodePort
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-codeready-workspace
  name: golang-codeready-workspace
  namespace: codeready-workspace  ##CHANGE ME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-codeready-workspace
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golang-codeready-workspace
    spec:
      containers:
      - image: quay.io/alberthua/golang-code-server:v1.1
        imagePullPolicy: IfNotPresent
        name: golang-codeready-workspace
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: golang-codeready-workspace  ##CHANGE ME
      serviceAccountName: golang-codeready-workspace  ##CHANGE ME
      # JUST use this file in OpenShift environment:
      #   1. create service account: $ oc create serviceaccount <name> -n <namespace>
      #   2. add anyuid scc to service account: $ oc adm policy add-scc-to-user anyuid -z <serviceaccount> -n <namespace>
